included:
  - Uttr
  - UttrTests
  - UttrUITests

excluded:
  - DerivedData
  - .build
  - .swiftpm

disabled_rules:
  - trailing_comma

opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional
  - vertical_whitespace_closing_braces

line_length:
  warning: 120
  error: 160

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 50
  error: 80

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - x
    - y
    - i
