import Foundation

struct PricingConfig: Codable, Sendable {
    var revenueCatAPIKey: String = ""
    var weeklyProductID: String = "weekly"
    var monthlyProductID: String = "monthly"
    var annualProductID: String = "annual"
    var trialDurationDays: Int = 3
    var entitlementID: String = "uttr_pro"

    // MARK: - Web Billing

    /// Anonymous RevenueCat Web Purchase Link. Checkout opens in the default
    /// browser; the purchase joins this install only after redemption.
    var webPurchaseLink: String = ""

    /// Custom URL scheme generated by the RevenueCat dashboard. Must match the
    /// `CFBundleURLSchemes` entry in Info.plist or callbacks will not route.
    var callbackScheme: String = "uttr"

    /// Maps `SubscriptionPlan.rawValue` to the RevenueCat package identifier.
    var packageIDsByPlanID: [String: String] = [:]

    /// Display prices for the paywall. Web Billing products do not surface
    /// StoreKit localized pricing, so these ship with the build.
    var displayPrices: [String: String] = [:]

    /// RevenueCat customer portal. Used for "Manage Subscription" and as the
    /// recovery path for a customer restoring on a second Mac.
    var customerPortalLink: String = ""

    init(
        revenueCatAPIKey: String = "",
        weeklyProductID: String = "weekly",
        monthlyProductID: String = "monthly",
        annualProductID: String = "annual",
        trialDurationDays: Int = 3,
        entitlementID: String = "uttr_pro",
        webPurchaseLink: String = "",
        callbackScheme: String = "uttr",
        packageIDsByPlanID: [String: String] = [:],
        displayPrices: [String: String] = [:],
        customerPortalLink: String = ""
    ) {
        self.revenueCatAPIKey = revenueCatAPIKey
        self.weeklyProductID = weeklyProductID
        self.monthlyProductID = monthlyProductID
        self.annualProductID = annualProductID
        self.trialDurationDays = trialDurationDays
        self.entitlementID = entitlementID
        self.webPurchaseLink = webPurchaseLink
        self.callbackScheme = callbackScheme
        self.packageIDsByPlanID = packageIDsByPlanID
        self.displayPrices = displayPrices
        self.customerPortalLink = customerPortalLink
    }

    init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        revenueCatAPIKey = try container.decodeIfPresent(String.self, forKey: .revenueCatAPIKey) ?? ""
        weeklyProductID = try container.decodeIfPresent(String.self, forKey: .weeklyProductID) ?? "weekly"
        monthlyProductID = try container.decodeIfPresent(String.self, forKey: .monthlyProductID) ?? "monthly"
        annualProductID = try container.decodeIfPresent(String.self, forKey: .annualProductID) ?? "annual"
        trialDurationDays = try container.decodeIfPresent(Int.self, forKey: .trialDurationDays) ?? 3
        entitlementID = try container.decodeIfPresent(String.self, forKey: .entitlementID) ?? "uttr_pro"
        webPurchaseLink = try container.decodeIfPresent(String.self, forKey: .webPurchaseLink) ?? ""
        callbackScheme = try container.decodeIfPresent(String.self, forKey: .callbackScheme) ?? "uttr"
        packageIDsByPlanID = try container.decodeIfPresent([String: String].self, forKey: .packageIDsByPlanID) ?? [:]
        displayPrices = try container.decodeIfPresent([String: String].self, forKey: .displayPrices) ?? [:]
        customerPortalLink = try container.decodeIfPresent(String.self, forKey: .customerPortalLink) ?? ""
    }

    /// Parsed checkout link, or `nil` when the bundled configuration has no
    /// usable URL. A missing link disables checkout rather than crashing.
    var webPurchaseURL: URL? {
        guard !webPurchaseLink.isEmpty else { return nil }
        return URL(string: webPurchaseLink)
    }

    var customerPortalURL: URL? {
        guard !customerPortalLink.isEmpty else { return nil }
        return URL(string: customerPortalLink)
    }
}

enum PricingConfigLoader {
    static func load() -> PricingConfig {
        guard let url = Bundle.main.url(forResource: "PricingConfig", withExtension: "json"),
              let data = try? Data(contentsOf: url) else {
            return PricingConfig()
        }
        return load(data: data)
    }

    static func load(data: Data) -> PricingConfig {
        (try? JSONDecoder().decode(PricingConfig.self, from: data)) ?? PricingConfig()
    }
}
